# Generated by Django 3.2.8 on 2022-08-13 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('shift', models.CharField(choices=[('Late', 'late'), ('Early', 'early'), ('Long', 'long'), ('Night', 'night')], max_length=20)),
                ('client', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plutotimesheet.week')),
            ],
        ),
    ]
